FROM node:18-alpine

# Set work directory
WORKDIR /usr/src/app

# Copy package.json & package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --only=production
 

# Copy ALL backend source code
COPY . .

ENV MONGO_URI=mongodb://mongo:27017/crud


EXPOSE 3000
CMD ["node", "server.js"]
