# backend/Dockerfile
FROM node:18-alpine
WORKDIR /usr/src/app

# install dependencies
COPY backend/package*.json ./
RUN npm ci --only=production

# copy source
COPY backend/ .

ENV PORT=3000
EXPOSE 3000

CMD ["node", "server.js"]
